workspace = { members = [
    "session1/authentication",
    "session1/hello-world",
    "session1/login",
    "session1/login_manager",
    "session1/variable",
] }

[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
